#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Melisa K. Savich
url: 'https://melisasavich.com'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: Showcasing over 7 years of expertise in cybersecurity, I specialize in fuzzing techniques, CI/CD pipeline implementation, and system-level security engineering. As a leader in team development, I achieved a 20% increase in code quality. Over the past 3 years, I have successfully transitioned cybersecurity technologies, significantly enhancing national cyber infrastructure. Explore my resume to learn more about my innovative solutions and industry-leading projects.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blush
chrome_mobile_color: 0086a5 #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: G-L3B3C2WZER

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-sitemap

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
